//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grabacr07.KanColleViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grabacr07.KanColleViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ※近日実装予定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Implement_Oncoming {
            get {
                return ResourceManager.GetString("Common_Implement_Oncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知しない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Notifications_Disable {
            get {
                return ResourceManager.GetString("Common_Notifications_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Common_Notifications_NotImplemented {
            get {
                return ResourceManager.GetString("Common_Notifications_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Notifications_Title {
            get {
                return ResourceManager.GetString("Common_Notifications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Windows 8 以降) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Notifications_Windows8 {
            get {
                return ResourceManager.GetString("Common_Notifications_Windows8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦娘 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ShipGirl {
            get {
                return ResourceManager.GetString("Common_ShipGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Debug に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   これはテスト通知です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Debug_NotificationMessage {
            get {
                return ResourceManager.GetString("Debug_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Debug_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Debug_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建造ドック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard {
            get {
                return ResourceManager.GetString("Dockyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完成！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_Complete {
            get {
                return ResourceManager.GetString("Dockyard_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建造中の艦名をネタバレする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_Display_Reveal {
            get {
                return ResourceManager.GetString("Dockyard_Display_Reveal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_Display_Title {
            get {
                return ResourceManager.GetString("Dockyard_Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロックされています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_Locked {
            get {
                return ResourceManager.GetString("Dockyard_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   工廠第 {0} ドックでの{1}の建造が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_NotificationMessage {
            get {
                return ResourceManager.GetString("Dockyard_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建造完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Dockyard_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建造完了時に通知を表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_Notifications_Enable {
            get {
                return ResourceManager.GetString("Dockyard_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドックごとに個別に設定する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_Notifications_Individual {
            get {
                return ResourceManager.GetString("Dockyard_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建造中の艦 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_ShipName {
            get {
                return ResourceManager.GetString("Dockyard_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion.
        /// </summary>
        public static string Dockyard_TimeComplete {
            get {
                return ResourceManager.GetString("Dockyard_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string Dockyard_TimeRemaining {
            get {
                return ResourceManager.GetString("Dockyard_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未使用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_Unused {
            get {
                return ResourceManager.GetString("Dockyard_Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遠征 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Expedition {
            get {
                return ResourceManager.GetString("Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遠征に出ていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Expedition_NoExpedition {
            get {
                return ResourceManager.GetString("Expedition_NoExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」が遠征から帰投しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Expedition_NotificationMessage {
            get {
                return ResourceManager.GetString("Expedition_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遠征完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Expedition_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Expedition_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遠征帰投時に通知を表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Expedition_Notifications_Enable {
            get {
                return ResourceManager.GetString("Expedition_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊ごとに個別に設定する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Expedition_Notifications_Individual {
            get {
                return ResourceManager.GetString("Expedition_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion.
        /// </summary>
        public static string Expedition_TimeComplete {
            get {
                return ResourceManager.GetString("Expedition_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string Expedition_TimeRemaining {
            get {
                return ResourceManager.GetString("Expedition_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fleets {
            get {
                return ResourceManager.GetString("Fleets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制空戦力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fleets_AirSuperiorityPotential {
            get {
                return ResourceManager.GetString("Fleets_AirSuperiorityPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   平均 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fleets_Average {
            get {
                return ResourceManager.GetString("Fleets_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レベル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fleets_Level {
            get {
                return ResourceManager.GetString("Fleets_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高速艦隊 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fleets_Speed_Fast {
            get {
                return ResourceManager.GetString("Fleets_Speed_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   低速艦隊 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fleets_Speed_Slow {
            get {
                return ResourceManager.GetString("Fleets_Speed_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fleets_Total {
            get {
                return ResourceManager.GetString("Fleets_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   司令部 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Homeport_FleetHQ {
            get {
                return ResourceManager.GetString("Homeport_FleetHQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant Build:  .
        /// </summary>
        public static string Homeport_InstantBuild {
            get {
                return ResourceManager.GetString("Homeport_InstantBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant Repair:.
        /// </summary>
        public static string Homeport_InstantRepair {
            get {
                return ResourceManager.GetString("Homeport_InstantRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保有装備: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Homeport_NoOfEquipment {
            get {
                return ResourceManager.GetString("Homeport_NoOfEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   所属艦娘: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Homeport_NoOfShips {
            get {
                return ResourceManager.GetString("Homeport_NoOfShips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   総合 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IntegratedView {
            get {
                return ResourceManager.GetString("IntegratedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この艦隊は遠征中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_Expedition {
            get {
                return ResourceManager.GetString("MessageBar_Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///    完了時刻: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_Expedition_TimeCompletion {
            get {
                return ResourceManager.GetString("MessageBar_Expedition_TimeCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///    帰投まで: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_Expedition_TimeRemaining {
            get {
                return ResourceManager.GetString("MessageBar_Expedition_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊に入渠中の艦娘がいます。 完了時刻: {0:MM/dd HH\:mm} 完了まで: {1}:{2:mm\:ss} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_Repairing {
            get {
                return ResourceManager.GetString("MessageBar_Repairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊に入渠中の艦娘がいます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_Repairing_Null {
            get {
                return ResourceManager.GetString("MessageBar_Repairing_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   疲労中の艦娘 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_ReSortie_BadCondition {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_BadCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊に{0}がいます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_ReSortie_CanNotReSortie {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_CanNotReSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出撃可能！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_ReSortie_CanReSortie {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_CanReSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未補給の艦娘 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_ReSortie_LackForResources {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_LackForResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再出撃までの目安:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_ReSortie_Remaining {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ・ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_ReSortie_Separator {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中破以上の艦娘 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_ReSortie_Wounded {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Wounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   任務画面の全ページにアクセスしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quest_Detail_Untaken {
            get {
                return ResourceManager.GetString("Quest_Detail_Untaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///    50 %  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quest_Progress_50 {
            get {
                return ResourceManager.GetString("Quest_Progress_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///    80 %  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quest_Progress_80 {
            get {
                return ResourceManager.GetString("Quest_Progress_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///    完了  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quest_State_Accomplished {
            get {
                return ResourceManager.GetString("Quest_State_Accomplished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (未取得の任務) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quest_Title_Untaken {
            get {
                return ResourceManager.GetString("Quest_Title_Untaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   任務 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quests {
            get {
                return ResourceManager.GetString("Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在遂行中の任務 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quests_CurrentQuestList {
            get {
                return ResourceManager.GetString("Quests_CurrentQuestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デイリー任務 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quests_Daily {
            get {
                return ResourceManager.GetString("Quests_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※進捗状況 (50 %, 80 %) はゲーム内の表示と同じです。敵艦隊の撃破数や遠征の成功回数のカウント等は行っていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quests_Notice {
            get {
                return ResourceManager.GetString("Quests_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲーム内で [任務 (クエスト)] 画面を開いて、任務一覧を取得してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quests_Untaken {
            get {
                return ResourceManager.GetString("Quests_Untaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィークリー任務 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quests_Weekly {
            get {
                return ResourceManager.GetString("Quests_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入渠ドック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Repairyard {
            get {
                return ResourceManager.GetString("Repairyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロックされています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Repairyard_Locked {
            get {
                return ResourceManager.GetString("Repairyard_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入渠第 {0} ドックでの「{1}」の整備が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Repairyard_NotificationMessage {
            get {
                return ResourceManager.GetString("Repairyard_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   整備完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Repairyard_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Repairyard_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   整備完了時に通知を表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Repairyard_Notifications_Enable {
            get {
                return ResourceManager.GetString("Repairyard_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドックごとに個別に設定する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Repairyard_Notifications_Individual {
            get {
                return ResourceManager.GetString("Repairyard_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入渠中の艦 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Repairyard_ShipName {
            get {
                return ResourceManager.GetString("Repairyard_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion.
        /// </summary>
        public static string Repairyard_TimeComplete {
            get {
                return ResourceManager.GetString("Repairyard_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string Repairyard_TimeRemaining {
            get {
                return ResourceManager.GetString("Repairyard_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未使用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Reparyard_Unused {
            get {
                return ResourceManager.GetString("Reparyard_Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「{0}」 in {1} is in critical condition!.
        /// </summary>
        public static string ReSortie_CriticalConditionMessage {
            get {
                return ResourceManager.GetString("ReSortie_CriticalConditionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Ship Warning.
        /// </summary>
        public static string ReSortie_CriticalConditionMessage_Title {
            get {
                return ResourceManager.GetString("ReSortie_CriticalConditionMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All ships in 「{0}」 have fully recovered from fatigue..
        /// </summary>
        public static string ReSortie_NotificationMessage {
            get {
                return ResourceManager.GetString("ReSortie_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   疲労回復完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReSortie_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("ReSortie_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクリーンショットの保存に失敗しました:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Screenshot_Failed {
            get {
                return ResourceManager.GetString("Screenshot_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクリーンショットを保存しました:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Screenshot_Saved {
            get {
                return ResourceManager.GetString("Screenshot_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change window color when a ship is in critical condition.
        /// </summary>
        public static string Settings_Accent_CriticalCondition {
            get {
                return ResourceManager.GetString("Settings_Accent_CriticalCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        public static string Settings_BrowserControl {
            get {
                return ResourceManager.GetString("Settings_BrowserControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ズーム倍率を 100 % に戻す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_BrowserControl_ClearZoomFactorButton {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_ClearZoomFactorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (表示) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_BrowserControl_Display {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ゲームのページから移動します。ご注意ください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_BrowserControl_Notice {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Display {
            get {
                return ResourceManager.GetString("Settings_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Condition.
        /// </summary>
        public static string Settings_FleetCondition {
            get {
                return ResourceManager.GetString("Settings_FleetCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string Settings_Logging {
            get {
                return ResourceManager.GetString("Settings_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log drops and crafting results to file.
        /// </summary>
        public static string Settings_Logging_Enable {
            get {
                return ResourceManager.GetString("Settings_Logging_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string Settings_Network {
            get {
                return ResourceManager.GetString("Settings_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give a notification for ships in critical condition.
        /// </summary>
        public static string Settings_Notify_CriticalCondition {
            get {
                return ResourceManager.GetString("Settings_Notify_CriticalCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviour.
        /// </summary>
        public static string Settings_Operation {
            get {
                return ResourceManager.GetString("Settings_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Other {
            get {
                return ResourceManager.GetString("Settings_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロキシ設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Proxy {
            get {
                return ResourceManager.GetString("Settings_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通信にプロキシ サーバーを使用する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Proxy_Enable {
            get {
                return ResourceManager.GetString("Settings_Proxy_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SSL 接続時もプロキシサーバーを使用する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Proxy_Enable_4_SSL {
            get {
                return ResourceManager.GetString("Settings_Proxy_Enable_4_SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Proxy_Host {
            get {
                return ResourceManager.GetString("Settings_Proxy_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Proxy_Port {
            get {
                return ResourceManager.GetString("Settings_Proxy_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクリーンショット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Screenshot {
            get {
                return ResourceManager.GetString("Settings_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Screenshot_FolderSelectionDialog_OpenButton {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderSelectionDialog_OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクリーンショットの保存先を指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Screenshot_FolderSelectionDialog_Title {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderSelectionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Screenshot_FolderTextBox_Label {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderTextBox_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存先フォルダーのパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Screenshot_FolderTextBox_Prompt {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderTextBox_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像形式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Screenshot_ImageFormat_Label {
            get {
                return ResourceManager.GetString("Settings_Screenshot_ImageFormat_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダーを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Screenshot_OpenFolderButton {
            get {
                return ResourceManager.GetString("Settings_Screenshot_OpenFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string Settings_Translations {
            get {
                return ResourceManager.GetString("Settings_Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append untranslated items to the translation files?.
        /// </summary>
        public static string Settings_Translations_Add_Enable {
            get {
                return ResourceManager.GetString("Settings_Translations_Add_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate game items, ships, and quests to selected language?.
        /// </summary>
        public static string Settings_Translations_Enable {
            get {
                return ResourceManager.GetString("Settings_Translations_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Settings_Updates {
            get {
                return ResourceManager.GetString("Settings_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically update translations on startup.
        /// </summary>
        public static string Settings_Updates_AutoUpdateTrans {
            get {
                return ResourceManager.GetString("Settings_Updates_AutoUpdateTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for the latest program and translation versions.
        /// </summary>
        public static string Settings_Updates_CheckUpdateButn_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Updates_CheckUpdateButn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string Settings_Updates_CheckUpdatesBtn {
            get {
                return ResourceManager.GetString("Settings_Updates_CheckUpdatesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently.
        /// </summary>
        public static string Settings_Updates_CurrentVersion {
            get {
                return ResourceManager.GetString("Settings_Updates_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Settings_Updates_OnlineVersion {
            get {
                return ResourceManager.GetString("Settings_Updates_OnlineVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on startup.
        /// </summary>
        public static string Settings_Updates_UpdateOnStartup {
            get {
                return ResourceManager.GetString("Settings_Updates_UpdateOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Translations.
        /// </summary>
        public static string Settings_Updates_UpdateTransBtn {
            get {
                return ResourceManager.GetString("Settings_Updates_UpdateTransBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads translations only for selected UI language!.
        /// </summary>
        public static string Settings_Updates_UpdateTransBtn_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Updates_UpdateTransBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Info.
        /// </summary>
        public static string Settings_VersionInfo {
            get {
                return ResourceManager.GetString("Settings_VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Window {
            get {
                return ResourceManager.GetString("Settings_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウを常に最前面に表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Window_TopMost {
            get {
                return ResourceManager.GetString("Settings_Window_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ操作 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_WindowControl {
            get {
                return ResourceManager.GetString("Settings_WindowControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウをモニターの左端に寄せる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_WindowControl_LocationLeftButton {
            get {
                return ResourceManager.GetString("Settings_WindowControl_LocationLeftButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8 インチタブレット (800 x 1280) 用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_WindowControl_LocationLeftButton_Sub {
            get {
                return ResourceManager.GetString("Settings_WindowControl_LocationLeftButton_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャッシュの削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartContent_ClearCacheButton {
            get {
                return ResourceManager.GetString("StartContent_ClearCacheButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャッシュを削除しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartContent_ClearCacheButtonMessage {
            get {
                return ResourceManager.GetString("StartContent_ClearCacheButtonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Cookie Region.
        /// </summary>
        public static string StartContent_SetRegionCookieButton {
            get {
                return ResourceManager.GetString("StartContent_SetRegionCookieButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie has been set.
        /// </summary>
        public static string StartContent_SetRegionCookieMessage {
            get {
                return ResourceManager.GetString("StartContent_SetRegionCookieMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure DMM.com is set to Japanese (日本語).
        /// </summary>
        public static string StartContent_SetRegionCookieToolTip {
            get {
                return ResourceManager.GetString("StartContent_SetRegionCookieToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string Stats_Accuracy {
            get {
                return ResourceManager.GetString("Stats_Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti-Air.
        /// </summary>
        public static string Stats_AntiAir {
            get {
                return ResourceManager.GetString("Stats_AntiAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti-Sub.
        /// </summary>
        public static string Stats_AntiSub {
            get {
                return ResourceManager.GetString("Stats_AntiSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        public static string Stats_Armor {
            get {
                return ResourceManager.GetString("Stats_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Rng.
        /// </summary>
        public static string Stats_AttackRange {
            get {
                return ResourceManager.GetString("Stats_AttackRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bombing.
        /// </summary>
        public static string Stats_DiveBomb {
            get {
                return ResourceManager.GetString("Stats_DiveBomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evasion.
        /// </summary>
        public static string Stats_Evasion {
            get {
                return ResourceManager.GetString("Stats_Evasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firepower.
        /// </summary>
        public static string Stats_Firepower {
            get {
                return ResourceManager.GetString("Stats_Firepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string Stats_Health {
            get {
                return ResourceManager.GetString("Stats_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luck.
        /// </summary>
        public static string Stats_Luck {
            get {
                return ResourceManager.GetString("Stats_Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sight Rng.
        /// </summary>
        public static string Stats_SightRange {
            get {
                return ResourceManager.GetString("Stats_SightRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Stats_Speed {
            get {
                return ResourceManager.GetString("Stats_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torpedo.
        /// </summary>
        public static string Stats_Torpedo {
            get {
                return ResourceManager.GetString("Stats_Torpedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Superiority Potential:.
        /// </summary>
        public static string StartContent_Introduction1 {
            get {
                return ResourceManager.GetString("StartContent_Introduction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ようこそ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartContent_Welcom {
            get {
                return ResourceManager.GetString("StartContent_Welcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦これの起動を待っています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusBar_NotStarted {
            get {
                return ResourceManager.GetString("StatusBar_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   準備完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusBar_Ready {
            get {
                return ResourceManager.GetString("StatusBar_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ズーム {0} % はサポートされていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZoomAction_OutOfRange {
            get {
                return ResourceManager.GetString("ZoomAction_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ズームに失敗しました: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZoomAction_ZoomFailed {
            get {
                return ResourceManager.GetString("ZoomAction_ZoomFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Level (Average):.
        /// </summary>
        public static string StatusBar_TotalAverageLevel {
            get {
                return ResourceManager.GetString("StatusBar_TotalAverageLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator.
        /// </summary>
        public static string Tools_Calculator {
            get {
                return ResourceManager.GetString("Tools_Calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Level.
        /// </summary>
        public static string Tools_Calculator_CurrentLevel {
            get {
                return ResourceManager.GetString("Tools_Calculator_CurrentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flagship.
        /// </summary>
        public static string Tools_Calculator_Flagship {
            get {
                return ResourceManager.GetString("Tools_Calculator_Flagship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Ship Girl.
        /// </summary>
        public static string Tools_Calculator_ListPrompt {
            get {
                return ResourceManager.GetString("Tools_Calculator_ListPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Tools_Calculator_Map {
            get {
                return ResourceManager.GetString("Tools_Calculator_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVP.
        /// </summary>
        public static string Tools_Calculator_MVP {
            get {
                return ResourceManager.GetString("Tools_Calculator_MVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string Tools_Calculator_RemainingExp {
            get {
                return ResourceManager.GetString("Tools_Calculator_RemainingExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Tools_Calculator_Result {
            get {
                return ResourceManager.GetString("Tools_Calculator_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortie Exp.
        /// </summary>
        public static string Tools_Calculator_SortieExp {
            get {
                return ResourceManager.GetString("Tools_Calculator_SortieExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Level.
        /// </summary>
        public static string Tools_Calculator_TargetLevel {
            get {
                return ResourceManager.GetString("Tools_Calculator_TargetLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rankings.
        /// </summary>
        public static string Tools_Rankings {
            get {
                return ResourceManager.GetString("Tools_Rankings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Tools_Rankings_Comment {
            get {
                return ResourceManager.GetString("Tools_Rankings_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string Tools_Rankings_Experience {
            get {
                return ResourceManager.GetString("Tools_Rankings_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Tools_Rankings_Level {
            get {
                return ResourceManager.GetString("Tools_Rankings_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page:.
        /// </summary>
        public static string Tools_Rankings_Page {
            get {
                return ResourceManager.GetString("Tools_Rankings_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Tools_Rankings_Rank {
            get {
                return ResourceManager.GetString("Tools_Rankings_Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Rankings.
        /// </summary>
        public static string Tools_Rankings_RankingsList {
            get {
                return ResourceManager.GetString("Tools_Rankings_RankingsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Tools_Rankings_Rate {
            get {
                return ResourceManager.GetString("Tools_Rankings_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Ranked:.
        /// </summary>
        public static string Tools_Rankings_TotalRanked {
            get {
                return ResourceManager.GetString("Tools_Rankings_TotalRanked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Tools_Rankings_User {
            get {
                return ResourceManager.GetString("Tools_Rankings_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KCV was unable to check for updates!.
        /// </summary>
        public static string Updater_Notification_CheckFailed {
            get {
                return ResourceManager.GetString("Updater_Notification_CheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version of KCV is available! 「v{0}」.
        /// </summary>
        public static string Updater_Notification_NewAppVersion {
            get {
                return ResourceManager.GetString("Updater_Notification_NewAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KanColleViewer Updater.
        /// </summary>
        public static string Updater_Notification_Title {
            get {
                return ResourceManager.GetString("Updater_Notification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KCV was unable to download the translations!.
        /// </summary>
        public static string Updater_Notification_TransUpdate_Fail {
            get {
                return ResourceManager.GetString("Updater_Notification_TransUpdate_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations are already up-to-date.
        /// </summary>
        public static string Updater_Notification_TransUpdate_Same {
            get {
                return ResourceManager.GetString("Updater_Notification_TransUpdate_Same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation files have been updated!.
        /// </summary>
        public static string Updater_Notification_TransUpdate_Success {
            get {
                return ResourceManager.GetString("Updater_Notification_TransUpdate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% zoom is not supported..
        /// </summary>
        public static string ZoomFactorSelector {
            get {
                return ResourceManager.GetString("ZoomFactorSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲーム画面の表示サイズを調整 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZoomFactorSelector_Tooltip {
            get {
                return ResourceManager.GetString("ZoomFactorSelector_Tooltip", resourceCulture);
            }
        }
    }
}
